<?php
/**
 * DraftCraft — AI Drafts Queue Tab View
 *
 * @package DraftCraft
 * @since   1.2.1
 *
 * @var array  $settings   Plugin settings array.
 * @var string $active_tab Currently active tab key.
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="draftcraft-panel <?php echo 'drafts' === $active_tab ? 'is-active' : ''; ?>" id="draftcraft-panel-drafts">

	<div class="draftcraft-section">
		<div class="draftcraft-section-header">
			<h2><?php esc_html_e( 'AI Drafts Queue', 'draftcraft' ); ?></h2>
			<p><?php esc_html_e( 'These are the posts generated by DraftCraft that are currently saved as drafts. Review, edit, and publish them when they are ready.', 'draftcraft' ); ?></p>
		</div>
		<div class="draftcraft-section-body">
			<?php
            // phpcs:disable WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- Filtered drafts queue by plugin meta flag.
			$draftcraft_drafts_query = new WP_Query(
				array(
					'post_type'      => 'post',
					'post_status'    => 'draft',
					'posts_per_page' => 10,
					'meta_query'     => array(
						array(
							'key'   => '_draftcraft_generated',
							'value' => '1',
						),
					),
					'orderby'        => 'date',
					'order'          => 'DESC',
				)
			);
            // phpcs:enable WordPress.DB.SlowDBQuery.slow_db_query_meta_query

			if ( $draftcraft_drafts_query->have_posts() ) :
				?>
				<div class="draftcraft-drafts-list">
					<table class="wp-list-table widefat fixed striped table-view-list posts" style="border:1px solid var(--dc-border-subtle); border-radius:var(--dc-radius); box-shadow:none; overflow:hidden;">
						<thead>
							<tr>
								<th scope="col" style="padding:12px 14px; font-weight:600; color:var(--dc-text);"><?php esc_html_e( 'Title', 'draftcraft' ); ?></th>
								<th scope="col" style="padding:12px 14px; font-weight:600; color:var(--dc-text); width:25%;"><?php esc_html_e( 'Categories', 'draftcraft' ); ?></th>
								<th scope="col" style="padding:12px 14px; font-weight:600; color:var(--dc-text); width:20%;"><?php esc_html_e( 'Date Generated', 'draftcraft' ); ?></th>
								<th scope="col" style="padding:12px 14px; font-weight:600; color:var(--dc-text); text-align:right; width:140px;"><?php esc_html_e( 'Actions', 'draftcraft' ); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php
							while ( $draftcraft_drafts_query->have_posts() ) :
								$draftcraft_drafts_query->the_post();
								$draftcraft_post_categories = get_the_category();
								$draftcraft_cat_names       = array();
								foreach ( $draftcraft_post_categories as $draftcraft_cat ) {
									$draftcraft_cat_names[] = $draftcraft_cat->name;
								}
								?>
								<tr>
									<td class="title column-title" style="padding:12px 14px; vertical-align:middle;">
										<strong><a class="row-title" href="<?php echo esc_url( get_edit_post_link( get_the_ID() ) ); ?>" style="color:var(--dc-text);"><?php the_title(); ?></a></strong>
									</td>
									<td class="categories column-categories" style="padding:12px 14px; vertical-align:middle; color:var(--dc-text-secondary);">
										<?php echo ! empty( $draftcraft_cat_names ) ? esc_html( implode( ', ', $draftcraft_cat_names ) ) : '—'; ?>
									</td>
									<td class="date column-date" style="padding:12px 14px; vertical-align:middle; color:var(--dc-text-muted); font-size:12.5px;">
										<?php echo esc_html( get_the_date( 'M d, Y @ h:i a' ) ); ?>
									</td>
									<td class="actions" style="padding:12px 14px; text-align:right; vertical-align:middle;">
										<a href="<?php echo esc_url( get_edit_post_link( get_the_ID() ) ); ?>" class="draftcraft-btn draftcraft-btn--sm draftcraft-btn--primary" style="margin-right:4px;">
											<span class="dashicons dashicons-edit"></span>
											<?php esc_html_e( 'Edit', 'draftcraft' ); ?>
										</a>
										<a href="<?php echo esc_url( get_preview_post_link( get_the_ID() ) ); ?>" class="draftcraft-btn draftcraft-btn--sm" target="_blank" rel="noopener noreferrer">
											<span class="dashicons dashicons-external"></span>
											<?php esc_html_e( 'Preview', 'draftcraft' ); ?>
										</a>
									</td>
								</tr>
								<?php
							endwhile;
							wp_reset_postdata();
							?>
						</tbody>
					</table>
					
					<?php if ( $draftcraft_drafts_query->found_posts > 10 ) : ?>
						<div style="margin-top:16px; text-align:center;">
							<a href="<?php echo esc_url( admin_url( 'edit.php?post_type=post&draftcraft_filter=1&post_status=draft' ) ); ?>" class="draftcraft-btn draftcraft-btn--primary">
								<?php
								printf(
									/* translators: %d: total number of generated draft posts. */
									esc_html__( 'View All Drafts (%d total)', 'draftcraft' ),
									(int) $draftcraft_drafts_query->found_posts
								);
								?>
							</a>
						</div>
					<?php endif; ?>
				</div>
			<?php else : ?>
				<div class="draftcraft-empty-state" style="text-align:center; padding:44px 20px; background:var(--dc-surface-alt); border:1px dashed var(--dc-border); border-radius:var(--dc-radius);">
					<span class="dashicons dashicons-media-document" style="font-size:44px; width:44px; height:44px; color:var(--dc-primary); margin-bottom:12px;"></span>
					<h3 style="margin:0 0 6px; font-size:16px; color:var(--dc-text);"><?php esc_html_e( 'No generated drafts found', 'draftcraft' ); ?></h3>
					<p style="color:var(--dc-text-muted); max-width:440px; margin:0 auto 20px; font-size:13px;"><?php esc_html_e( 'When DraftCraft generates articles as drafts, they will appear here for your editorial review and publishing.', 'draftcraft' ); ?></p>
					<div style="display:flex; justify-content:center; gap:10px; flex-wrap:wrap;">
						<a href="<?php echo esc_url( admin_url( 'admin.php?page=draftcraft&tab=schedule' ) ); ?>" class="draftcraft-btn draftcraft-btn--primary">
							<span class="dashicons dashicons-clock"></span>
							<?php esc_html_e( 'Configure Automation Schedule', 'draftcraft' ); ?>
						</a>
						<button type="button" class="draftcraft-btn" onclick="document.getElementById('draftcraft-manual-trigger')?.click();">
							<span class="dashicons dashicons-controls-play"></span>
							<?php esc_html_e( 'Generate Post Now', 'draftcraft' ); ?>
						</button>
					</div>
				</div>
			<?php endif; ?>
		</div>
	</div>

</div><!-- /#draftcraft-panel-drafts -->
